version: "3.7"

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "10000:10000"
    expose:
      - "9092"
      - "10000"
    environment:
      # == Kafka KRaft 설정 ==
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NODE_ID: 0
      KAFKA_BROKER_ID: 0
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      # === Listener 설정 ===
      KAFKA_ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:10000"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://${KAFKA_URL}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      # == Cluster 설정 ==
      KAFKA_CREATE_TOPICS: "otel-traces:3:1"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      # === 수신 크기 제한 변경 ===
      KAFKA_SOCKET_REQUEST_MAX_BYTES: "100000000"  # (200MB, 기본 100MB)
      KAFKA_MESSAGE_MAX_BYTES: "1000000"        # (1MB, 기본 1MB)
      KAFKA_MAX_REQUEST_SIZE: "1000000"         # (1MB, 기본 1MB)
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-Kraft-Cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTER_0_AUDIT_TOPICAUDITENABLED: "true"
      KAFKA_CLUSTER_0_CONSOLEAUDITENABLED: "true"
    depends_on:
      - kafka
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  kafka-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./kafka-data
  
  