version: "3.7"

services:
  kafka-broker00:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker00
    restart: always
    ports:
      - "19092:19092"
    expose:
      - "19092"
    environment:
      # == Kafka KRaft 설정 ==
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NODE_ID: 0
      KAFKA_BROKER_ID: 0
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka-broker00:9093,1@kafka-broker01:9093,2@kafka-broker02:9093"
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      # === Listener 설정 ===
      KAFKA_ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker00:9092,CONTROLLER://kafka-broker00:9093,EXTERNAL://${KAFKA_URL}:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      # == Cluster 설정 ==
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - kafka-broker00-data:/var/lib/kafka/data
    networks:
      - kafka-network
    
  kafka-broker01:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker01
    restart: always
    ports:
      - "29092:29092"
    expose:
      - "29092"
    environment:
      # == Kafka KRaft 설정 ==
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka-broker00:9093,1@kafka-broker01:9093,2@kafka-broker02:9093"
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      # === Listener 설정 ===
      KAFKA_ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker01:9092,CONTROLLER://kafka-broker01:9093,EXTERNAL://${KAFKA_URL}:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - kafka-broker01-data:/var/lib/kafka/data
    networks:
      - kafka-network

  kafka-broker02:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker02
    restart: always
    ports:
      - "39092:39092"
    expose:
      - "39092"
    environment:
      # == Kafka KRaft 설정 ==
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka-broker00:9093,1@kafka-broker01:9093,2@kafka-broker02:9093"
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      # === Listener 설정 ===
      KAFKA_ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:39092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker02:9092,CONTROLLER://kafka-broker02:9093,EXTERNAL://${KAFKA_URL}:39092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - kafka-broker02-data:/var/lib/kafka/data
    networks:
      - kafka-network



  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-Kraft-Cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-broker00:9092,kafka-broker01:9092,kafka-broker02:9092"
      KAFKA_CLUSTER_0_METRICS_PORT: "9999"
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTER_0_AUDIT_TOPICAUDITENABLED: "true"
      KAFKA_CLUSTER_0_CONSOLEAUDITENABLED: "true"
    depends_on:
      - kafka-broker00
      - kafka-broker01
      - kafka-broker02
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  
  kafka-broker00-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./kafka-broker00-data
  
  kafka-broker01-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./kafka-broker01-data
  
  kafka-broker02-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./kafka-broker02-data