version: "3.7"

services:
  otel-router:
    image: otel/opentelemetry-collector-contrib:latest
    # image: otel/opentelemetry-collector-contrib:0.43.0
    container_name: otel-router
    restart: always
    volumes:
      - ./config/config.yml/:/etc/opentelemetry-collector.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--config=/etc/opentelemetry-collector.yml"
    ports:
      - 1888:1888   # pprof extension
      - 4317:4317   # otlp grpc receiver
      - 4318:4318   # otlp http receiver
      - 13133:13133 # health check extension
    environment:
      - KAFKA_LOGS_URLS=${KAFKA_LOGS_URLS}
    expose:
      - "4317"
    depends_on:
      - jaeger-collector
    networks:
      - route-net

  jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    container_name: router-jaeger-collector
    ports:
      - "14250"
      - "4318"
      - "4317"
    networks:
      - route-net
    restart: on-failure
    environment:
      SPAN_STORAGE_TYPE: "kafka"
    command: [
      "--kafka.producer.brokers=${KAFKA_TRACE_URLS}",
      "--kafka.producer.topic=otel-traces",
      "--kafka.producer.tls.enabled=false",
      "--kafka.producer.encoding=protobuf",
      "--log-level=debug",
    ]

networks:
  route-net:
    driver: bridge